### ISSUE TITLE
如何添加自己的iconfont图标?

### ISSUE THREAD

**Issue by maimake** [TalkingData/iview-weapp#101]
我们项目也是使用icontfont，请教怎样能让i-icon既能使用iview的图标，也能使用我们项目的图标

**Comment by lonquan** [comment]
直接引入 iconfont 的字体不就好了... 没必要非要加在  i-icon 中

**Comment by icarusion** [comment]
下个版本支持自定义 icon

**Comment by billyshen26** [comment]
> 下个版本支持自定义 icon

请问能给一个示例么，怎么用自己的iconfont,官网没给出怎么用的示例
