### ISSUE TITLE
列表点击事件问题

### ISSUE THREAD

**Issue by peng0208** [TalkingData/iview-weapp#102]
列表，只能跳转到url或者事件返回event，那如何返回列表的属性的值呢？因为我要取到值去做一个请求，而不是简单的URL跳转。还是我不会用，求助

**Comment by lonquan** [comment]
data-*

**Comment by peng0208** [comment]
可以详细说下么，我也是刚学。绑定事件好像也不能传递参数，如果支持原生绑定事件就好了

**Comment by peng0208** [comment]
感谢，已明白
