### ISSUE TITLE
i-input 组件，type !== 'textarea'的时候，不能正确的触发input事件

### ISSUE THREAD

**Issue by moonshadow-miao** [TalkingData/iview-weapp#126]
如题，i-input组件不能正确的触发input事件，其他事件（blur, change, foucs）正常。 但是通过手机调试，控制台的info中，确实有显示 ‘invoke event handleInputChange in component:。。。’，组件内部的状态data：value为null，很困扰，希望得到解答。

**Comment by moonshadow-miao** [comment]
小程序版本是2.2.0

**Comment by zmGitHub** [comment]
窝草 老哥 你咋自己关了 啥问题 咋解决的?
