### ISSUE TITLE
为什么我在使用i-class都不生效呢？

### ISSUE THREAD

**Issue by ycc3000** [TalkingData/iview-weapp#134]
![c111](https://user-images.githubusercontent.com/22928461/43723010-3b5d8134-99c9-11e8-9c17-a8bbba1339f1.PNG)
![c22](https://user-images.githubusercontent.com/22928461/43723024-4131054a-99c9-11e8-8d92-21c7fa6b5f29.PNG)

**Comment by CTM-TT** [comment]
我也不生效，能解决吗

**Comment by ycc3000** [comment]
他们根本就不会理你，或许是问题太幼稚，是因为版本必须是..90以上才支持，把版本提高一下就可以了。

**Comment by Choujiji** [comment]
@ycc3000 请问是什么.90以上？
