### ISSUE TITLE
官网报错，点击 开始使用无法查看

### ISSUE THREAD

**Issue by januwA** [TalkingData/iview-weapp#147]
![image](https://user-images.githubusercontent.com/22570563/44071104-d03274a4-9fb9-11e8-9425-4df22d91489b.png)

**Comment by FxPixels** [comment]
我也遇到同样的问题

**Comment by leevane** [comment]
感觉没人维护了。

**Comment by icarusion** [comment]
缓存或网络问题，各种清缓存强刷新试试，看看手机网络能不能打开。

**Comment by tangsj** [comment]
同样的错。 一直打不开，  是不是cdn 缓存 没刷上啊， 坐标重庆！
