### ISSUE TITLE
微信小程序怎么获取iview weapp中i-input的值

### ISSUE THREAD

**Issue by hzy101552** [TalkingData/iview-weapp#159]
<i-input value="{{ phone }}" title="联系电话" type='number' bind:blur="sendPhone"  bind:change="phoneInput"></i-input>
phoneInput: function (e) {
    var that = this;
    that.setData({
      phone: e.detail.value,
    })
  },
这样不管用啊

**Comment by rocco0505** [comment]
e.detail.value 取不到，把 function(e) 换成 function({detail})

**Comment by peetaxie** [comment]
应该是e.detail.detail.value
