### ISSUE TITLE
建议，文档放一张该效果的gif图

### ISSUE THREAD

**Issue by albertli2333** [TalkingData/iview-weapp#186]
网站上的文档我觉得在最后放一张该效果的gif图比较好，这样可以一路看下去，就不用去运行demo然后两边看了。纯粹个人意见，不喜勿喷。

**Comment by zddapi** [comment]
支持楼主

**Comment by liuxiaojin93** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
