### ISSUE TITLE
下载之后测试无法运行

### ISSUE THREAD

**Issue by ljt1469** [TalkingData/iview-weapp#19]
您好，我将github仓库上所有代码打包下载到本地。解压iview-weapp-master之后，我将dist文件夹拷贝到example文件夹中。然后使用PC端的开发者工具是可以打开示例的。然而，当我使用远程调试的时候，在手机端是无法查看例子的，即页面没有渲染出来。并且在控制台显示：
WXMLRT_$gwx:./pages/icon/index.wxml:view:2:6: Now you can provide attr `wx:key` for a `wx:for` to improve performance.

我的微信和开发者工具均为最新版，手机型号为iphone6s和华为。

在官网上的二维码进入demo是没有问题的，文档中的npm方式未尝试。

请问这是什么问题呢？

**Comment by BuptStEve** [comment]
警告是因为没加 wx:key https://github.com/TalkingData/iview-weapp/pull/7/commits/26dc7887dccd4a9fbef17cbdadac31bb8c73e5d7

没加载出来应该是别的原因...

**Comment by icarusion** [comment]
应该是你微信开发者的问题。
