### ISSUE TITLE
微信编辑器中input无法输入

### ISSUE THREAD

**Issue by pp-tang** [TalkingData/iview-weapp#227]
微信编辑器中input无法输入。
微信编辑器版本v1.02.1809260
基础库版本2.3.0

**Comment by pp-tang** [comment]
电脑端编辑器使用  i-input  组件 无法输入字符

**Comment by demopark** [comment]
遇到同样的问题

**Comment by demopark** [comment]
i-input的 type 换成textarea就可以输入了,将就用吧,测试完了发布前再换回去.

**Comment by pp-tang** [comment]
> #246 已经解决

谢谢 看到了，你怎么想到这个 研究了源码吗？

**Comment by ayedaren8** [comment]
设置maxlength属性即可
