### ISSUE TITLE
npm run dev在哪个根目录下执行的？

### ISSUE THREAD

**Issue by Jovins** [TalkingData/iview-weapp#23]

**Comment by icarusion** [comment]
`package.json` 在哪就在哪执行。

**Comment by Jovins** [comment]
但是我在package.json目录下执行，出现了编译错误。这个是什么原因呀？
![Uploading image.png…](编译错误)

**Comment by Jovins** [comment]
但是我在package.json目录下执行，出现了编译错误。这个是什么原因呀？
JovinsdeMacBook-Pro:iview-weapp Jovins$ npm run dev

> iview-weapp@1.1.0 dev /Users/Jovins/Desktop/小程序/iview-weapp
> gulp --gulpfile build/build-dev.js

sh: gulp: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! iview-weapp@1.1.0 dev: `gulp --gulpfile build/build-dev.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the iview-weapp@1.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Jovins/.npm/_logs/2018-06-13T10_40_07_697Z-debug.log
