### ISSUE TITLE
每次看文档都要上代理

### ISSUE THREAD

**Issue by albertli2333** [TalkingData/iview-weapp#275]
有点烦躁，每次看官网那个文档都要上代理

**Comment by Maconzhang** [comment]
现在官网打开是白屏要如何设置？

**Comment by yuemingbo** [comment]
> 有点烦躁，每次看官网那个文档都要上代理

大佬 怎么上代理啊
我这都一个星期这样了 不知道怎么解决啊

**Comment by liuxiaojin93** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
