### ISSUE TITLE
`mpvue`引入`iview-weapp`示例，组件直接引入，修改较少源码

### ISSUE THREAD

**Issue by JJJYY** [TalkingData/iview-weapp#30]
目前没发现什么大问题，仅供参考  
项目改写自官方示例，除特殊情况外(文档有详细说明)不需要修改源码

[项目地址](https://github.com/JJJYY/mpvue-iview)
[插件地址](https://github.com/JJJYY/import-weapp-component)

**Comment by smartymoon** [comment]
it's great

**Comment by PythonNaChen** [comment]
sEnginScriptError
Component is not found in path "iview/button/index" (using by "pages/ysList/main")
Error: Component is not found in path "iview/button/index" (using by "pages/ysList/main")

按照你的目录结构，插件也下载了，项目也重启了，还是不行

**Comment by JJJYY** [comment]
`iview/button/index` => `/iview/button/index`，路径不对吧

**Comment by PythonNaChen** [comment]
除了 npm install和npm i -D import-weapp-component外，没别的配置吧，我下班后试下

**Comment by JJJYY** [comment]
我怀疑你没有引用插件

**Comment by PythonNaChen** [comment]
cnpm i -D import-weapp-component 之后，我就在build目录下创建了 webpack.config.js， 然后把：

const ImportComponent = require('import-weapp-component')
const config = {
  plugins: [
    new ImportComponent()
  ]
}

复制进去了

**Comment by JJJYY** [comment]
你有时间试下我的`DEMO`吧:joy:

**Comment by PythonNaChen** [comment]
大神，我又在另一台电脑上新建了一个项目，也报的找不到，然后我又去运行你的demo能跑得起来。啊啊啊有毒啊，

**Comment by JJJYY** [comment]
你对比下`build`下的文件，我`DEMO`里是在`webpack.base.conf.js`里面引入的，你看你是不是引入错了，应该是哪个地方配置出错了
```js
// webpack.base.conf.js
plugins: [
  new MpvuePlugin(),
  new ImportComponent()
]
```

**Comment by chengheai** [comment]
@PythonNaChen 大侠，问题解决了吗？出在哪里？

**Comment by PythonNaChen** [comment]
没有配置正确 @chengheai
