### ISSUE TITLE
[feature] document should be add a demo for mpvue

### ISSUE THREAD

**Issue by xkcoding** [TalkingData/iview-weapp#4]
document should be add a demo for mpvue

文档中应当添加一个使用 mpvue 的例子

**Comment by michael829** [comment]
同意..虽然我知道怎么用..不过还是写一些例子出来比较好...感谢..

**Comment by bigmeow** [comment]
请到mpvue中提问：如何在mpvue中使用原生小程序组件。
算了，还说一句好了，一个个都不看下小程序官网。把原生小程序组件拷贝到mpvue项目的static目录下，
那个页面要用到就在vue对应的main.js配置文件里写：
```json
"usingComponents": {
    "i-button": "/static/组件/组件入口.js"
}
```

**Comment by xkcoding** [comment]
@bigmeow 感谢回复！
ps：本人后端，只是在知乎看到 @Aresn 发的文章。过来看下。顺便给个建议。

**Comment by BuptStEve** [comment]
大兄弟不妨看看这个？https://github.com/TalkingData/iview-weapp/pull/7

**Comment by 976293711** [comment]
感谢大兄弟的教导，用mpvue使用上了iview-weapp 一直心念念着

**Comment by GrowthCoder** [comment]
@michael829 可以分享下怎么在mpvue中使用iview-webapp中么

**Comment by PythonNaChen** [comment]
@bigmeow 照你说的把iview weapp dist下的组件放到static里，再在vue对应的main.js里调用，还是没效果

**Comment by FrankRoc** [comment]
我刚写一个测试,用的mpvue的框架,加入了iview-weapp,发现部分组件可用,部分不可以,很是纠结,而且有些组件显示也跟官网的不太一致,准备放弃,转向mpvue-weui了.
