### ISSUE TITLE
i-button  微信开放能力bug

### ISSUE THREAD

**Issue by boot-vue** [TalkingData/iview-weapp#50]
i-button    open-type为getuserinfo时    无法绑定获取用户信息的事件  bindgetuserinfo无效

**Comment by wkl007** [comment]
感觉iview-weapp中有关open-type的组件都应该有特殊的事件处理。
例如这样
![例子](https://img-blog.csdn.net/20180629150050147?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM1ODQ0MTc3/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)
