### ISSUE TITLE
对话框i-modal的大小如何调整？

### ISSUE THREAD

**Issue by Hunterfish** [TalkingData/iview-weapp#51]
没看到具体参数！
![model](https://user-images.githubusercontent.com/25543945/41723741-72a100ca-759e-11e8-9cfd-a386e6ea26d8.png)
不知道怎么回事，设置了 show-ok、show-cancel 为 false，依然显示
`<i-modal title="今天干了啥" visible="{{ dayDialogVisible }}" show-ok="false" show-cancel="false" bind:cancel="closeDialog" i-class="modal-style">
  <i-row>
    <i-button...../>
  </i-row>
</i-modal>`

**Comment by stumpx** [comment]
1，先给i-modal设置i-class="mm"
```
<i-modal i-class="mm" title="标题" visible="{{ visible1 }}" bind:ok="handleClose1" bind:cancel="handleClose1">
    <view>一些文本</view>
    <view>一些文本</view>
    <view>一些文本</view>
    <view>一些文本</view>
    <view>一些文本</view>
    <view>一些文本</view>
    <view>一些文本</view>
    <view>一些文本</view>
    <view>一些文本</view>
</i-modal>
```
2，给mm写样式，.mm > view是.i-modal-main可以设置宽度，.mm > view > view > view:last-child是.i-modal-actions可以设置不显示，
```
.mm > view {
  width: 700rpx;
}

.mm > view > view > view:last-child{
  display: none;
}
```

**Comment by luniard** [comment]
如何去掉 max-height 这个属性
