### ISSUE TITLE
mpvue 引入iview-weapp的action-sheet组件,点击选项无法获取选项索引

### ISSUE THREAD

**Issue by xianer0405** [TalkingData/iview-weapp#71]
***bug
mpvue 引入iview-weapp的action-sheet组件,点击选项无法获取选项索引
![image](https://user-images.githubusercontent.com/3275868/42032804-547646fe-7b0d-11e8-8396-f4c8124ae96f.png)
![image](https://user-images.githubusercontent.com/3275868/42032814-597e3706-7b0d-11e8-942a-a269b68fce01.png)

**Comment by xianer0405** [comment]
在上层的vue界面选项的点击事件的回调函数内打印事件event对象, e.mp.detail和e.mp.currentTarget.dataset中都没有索引值.
代码如下: 
handleClickItem1(e) {
    console.log(e)
    console.log('点击了选项' + index)
},

**Comment by JiejiaH** [comment]
#10 下面有解决方案
